# version: "3.3"

# services:
#   edn_topology:
#     container_name: EDN_TOPOLOGY_REACT
#     restart: always
#     image: edn_topology_dashboard:v3
#     command: ["npm", "start"]
#     volumes:
#       - ./frontend:/frontend
#       - node-modules:/frontend/node_modules
#     ports:
#       - "3013:3000"

services:
  edn_topology:
    container_name: EDN_TOPOLOGY_REACT
    restart: always
    build:
      context: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    ports:
      - "3013:3000"

volumes:
  node-modules:

